### PR TITLE
add tree dimension as a generic parameter

### PR DESCRIPTION
**Pull request by RSDuck**

### CODE REVIEW

**Comment by jblindsay** [comment]
I'm sorry for the late reply. I went grocery shopping and it's end-of-days out there! Anyhow, when I returned, I saw that you had made this PR. It validated that the approach that I was taking was correct. It allowed me to repair my own code (I had K before T, which I think is more logical). I came to realize after inspecting your code that my error was in saying [K: static int, T] rather than [K: static[int]; T]. I think it was that semicolon that I was missing, although it may also have been the static[int] vs static int.

Anyhow, after getting the code correct, I did some testing and noticed the following:

1. nimsuggest really does not like this level of generic code. I've seen a few other people online with the same issue, but the new code basically broke nimsuggest and VSCode for me. It would run at 100% for long periods and leak memory until eventually crashing. It was unusable.

2. I could not get my tests to complete successfully. In particular, I wrote at test that created a 3D tree, and very oddly, it never returned the correct data value for the nearest point. It was incredibly unstable in this behaviour though. If I commented out all other tests, it would work, but with the other tests, this error would occur. I can think of no reason why this should occur and it seems to be a buggy behaviour.

3. Most importantly, the addition of the generic K degraded the performance of the library considerably. On one application that I am using a 2D tree for, it went from 5.5s to 8.1 seconds. A 47% degradation in performance just to be able to modify the dimension of the tree! In every application that I have, I really only need either a 2D, or rarely a 3D tree. I just can't accept a 47% degradation for that.

And so ultimately, I've decided to hold off on this change for now. I really do appreciate your efforts and the time that you spent on trying to improve this however. Thanks again.

**Comment by RSDuck** [comment]
> Most importantly, the addition of the generic K degraded the performance of the library considerably. On one application that I am using a 2D tree for, it went from 5.5s to 8.1 seconds. A 47% degradation in performance just to be able to modify the dimension of the tree! In every application that I have, I really only need either a 2D, or rarely a 3D tree. I just can't accept a 47% degradation for that.

this interests me, because it really shouldn't be the case. Have you compiled your code with `--d:danger` and `--opt:speed`?

**Comment by jblindsay** [comment]
I know, it really puzzled me as well. I realize that the compiler is simply substituting the static version of K in, and so it shouldn't affect performance on the face of it. However, I assumed that the extra complexity placing all the extra 'K' parameters on every type and function came at a cost compared with the original code. 

Honestly, my familiarity with Nim is not high and I have been building simply by using `nimble install`, which I'm sure is not right. I do believe that this creates a release version (`-d:release`) though. I'm not sure if this is right. I'm coming from Rust, where I'd just `cargo build --release`.

**Comment by RSDuck** [comment]
weird, can I take a look at your code?

**Comment by jblindsay** [comment]
Sure, do you have an email that I can forward it to?

**Comment by jblindsay** [comment]
I've just created a branch called 'generic-K' that you can examine the code within.

**Pull request closed without merging**
